FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY apps/api ./apps/api
COPY packages ./packages
RUN npm install --omit=dev
WORKDIR /app/apps/api
CMD ["node", "dist/index.js"]
